# Generated by Django 3.0.6 on 2020-05-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemicaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeating_units', models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block')], default='STATISTICAL', max_length=16)),
                ('monomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='PolymerStructure',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Structure')),
                ('big_smiles', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('chemicaldb.structure',),
        ),
        migrations.CreateModel(
            name='Polymer',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Substance')),
                ('polymer_structure_type', models.CharField(choices=[('LINEAR', 'linear'), ('BRANCHED', 'branched'), ('NETWORK', 'network')], default='LINEAR', max_length=16)),
                ('monomer_distribution', models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block')], default='STATISTICAL', max_length=12)),
                ('distribution_parameter', models.FloatField(default=1)),
                ('monomers', models.ManyToManyField(through='chemicaldb_polymers.Monomers', to='chemicaldb.Structure')),
                ('polymer_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polymer_structure', to='chemicaldb_polymers.PolymerStructure')),
            ],
            bases=('chemicaldb.substance',),
        ),
        migrations.AddField(
            model_name='monomers',
            name='polymer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p', to='chemicaldb_polymers.Polymer'),
        ),
    ]
