# Generated by Django 3.0.7 on 2020-06-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemicaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatingUnit',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Structure')),
                ('big_smiles', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('chemicaldb.structure',),
        ),
        migrations.CreateModel(
            name='StartEndGroup',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Structure')),
            ],
            options={
                'abstract': False,
            },
            bases=('chemicaldb.structure',),
        ),
        migrations.CreateModel(
            name='PolymerStructure',
            fields=[
                ('repeatingunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb_polymers.RepeatingUnit')),
                ('monomer_distribution', models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block'), ('MIXED', 'mixed')], default='STATISTICAL', max_length=12)),
                ('repeating_units', models.ManyToManyField(related_name='repeating_units', to='chemicaldb_polymers.RepeatingUnit')),
                ('terminal_end_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_polymer_endgroup', to='chemicaldb_polymers.StartEndGroup')),
                ('terminal_start_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_polymer_startgroup', to='chemicaldb_polymers.StartEndGroup')),
            ],
            options={
                'abstract': False,
            },
            bases=('chemicaldb_polymers.repeatingunit',),
        ),
        migrations.CreateModel(
            name='Polymer',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Substance')),
                ('polymer_structure_type', models.CharField(choices=[('LINEAR', 'linear'), ('BRANCHED', 'branched'), ('NETWORK', 'network')], default='LINEAR', max_length=16)),
                ('monomer_distribution', models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block'), ('MIXED', 'mixed')], default='STATISTICAL', max_length=12)),
                ('distribution_parameter', models.FloatField(default=1)),
                ('polymer_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polymer_structure', to='chemicaldb_polymers.PolymerStructure')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('chemicaldb.substance',),
        ),
    ]
