# Generated by Django 3.0.7 on 2020-06-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('chemicaldb_polymers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polymer',
            name='distribution_parameter',
        ),
        migrations.RemoveField(
            model_name='polymer',
            name='monomer_distribution',
        ),
        migrations.RemoveField(
            model_name='polymer',
            name='polymer_structure_type',
        ),
        migrations.AddField(
            model_name='polymerstructure',
            name='polymer_structure_type',
            field=models.CharField(choices=[('LINEAR', 'linear'), ('BRANCHED', 'branched'), ('NETWORK', 'network')], default='LINEAR', max_length=16),
        ),
        migrations.CreateModel(
            name='NumbeAverageMolarMass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_flag', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Source')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb_polymers.Polymer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassAverageMolarMass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_flag', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Source')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb_polymers.Polymer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlasTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_flag', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Source')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb_polymers.Polymer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
