# Generated by Django 3.0.6 on 2020-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb_polymers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monomers',
            name='repeating_units',
            field=models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block')], default='STATISTICAL', max_length=16),
        ),
        migrations.AlterField(
            model_name='polymer',
            name='monomer_distribution',
            field=models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block')], default='STATISTICAL', max_length=12),
        ),
    ]
