# Generated by Django 3.0.6 on 2020-06-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb_polymers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polymer',
            options={'base_manager_name': 'objects'},
        ),
    ]
