# Generated by Django 3.0.6 on 2020-06-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb_polymers', '0002_auto_20200602_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polymerstructure',
            options={'base_manager_name': 'objects'},
        ),
    ]
