# Generated by Django 3.0.7 on 2020-06-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0012_auto_20200610_0449'),
        ('chemicaldb_polymers', '0005_auto_20200609_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartEndGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, editable=False)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb.Structure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EndGroup',
        ),
        migrations.DeleteModel(
            name='StartGroup',
        ),
        migrations.AlterField(
            model_name='polymer',
            name='end_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_polymer_endgroup', to='chemicaldb_polymers.StartEndGroup'),
        ),
        migrations.AlterField(
            model_name='polymer',
            name='start_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_polymer_startgroup', to='chemicaldb_polymers.StartEndGroup'),
        ),
    ]
