# Generated by Django 3.0.7 on 2020-06-10 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0012_auto_20200610_0449'),
        ('chemicaldb_polymers', '0006_auto_20200610_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatingUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, editable=False)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb.Structure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='monomers',
            name='monomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb_polymers.RepeatingUnit'),
        ),
        migrations.AlterField(
            model_name='polymer',
            name='monomers',
            field=models.ManyToManyField(through='chemicaldb_polymers.Monomers', to='chemicaldb_polymers.RepeatingUnit'),
        ),
    ]
