# Generated by Django 3.0.7 on 2020-06-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb_polymers', '0007_auto_20200610_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymer',
            name='end_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_polymer_endgroup', to='chemicaldb_polymers.StartEndGroup'),
        ),
        migrations.AlterField(
            model_name='polymer',
            name='start_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_polymer_startgroup', to='chemicaldb_polymers.StartEndGroup'),
        ),
    ]
