version: '3'
services:
  chemdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8000"
    volumes:
      - ./django_settings.json:/django_settings.json
      - ./chemDB:/home/appuser/app/chemDB # dev only
      - ./requirements.txt:/requirements.txt  # dev only
      - ./docker-entrypoint.sh:/docker-entrypoint.sh  # dev only
#    command: tail -f /dev/null
    command: sh /docker-entrypoint.sh
    restart: always
    environment:
      MYSQL_USER: 'chem_db_user'
      MYSQL_PASSWORD: "VMG_fJUGMGfQbCED9W49o"
      MYSQL_DATABASE: 'chem_db_user'
      MYSQL_HOST: '172.27.33.2'
    #network_mode: "host"
    #depends_on:
     # - db