version: '3'
services:
  chemdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8000"
    volumes:
      - ./chemDB:/home/appuser/app/chemDB
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 &&
             python"
    restart: always
    environment:
      MYSQL_USER: 'chem_db_user'
      MYSQL_PASSWORD: "VMG_fJUGMGfQbCED9W49o"
      MYSQL_DATABASE: 'chem_db_user'
    network_mode: "host"
    #depends_on:
     # - db