version: '3'
services:
  chemdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./chemDB:/home/appuser/app/chemDB
    restart: always
    environment:
      MYSQL_USER: 'chem_db_user'
      MYSQL_PASSWORD: "VMG$fJUGMGfQbCED9W49o"
      MYSQL_DATABASE: 'chem_db_user'
    network_mode: "host"