# Generated by Django 3.0.6 on 2020-05-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0003_auto_20200511_0753'),
        ('substance', '0004_internal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copolymer',
            fields=[
                ('simplesubstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='substance.SimpleSubstance')),
                ('polymer_structure', models.CharField(choices=[('LINEAR', 'linear'), ('BRANCHED', 'branched'), ('NETWORK', 'network')], default='LINEAR', max_length=16)),
                ('monomer_distribution', models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block')], default='STATISTICAL', max_length=16)),
                ('distribution_factor', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('substance.simplesubstance',),
        ),
        migrations.CreateModel(
            name='HomoPolymer',
            fields=[
                ('simplesubstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='substance.SimpleSubstance')),
                ('polymer_structure', models.CharField(choices=[('LINEAR', 'linear'), ('BRANCHED', 'branched'), ('NETWORK', 'network')], default='LINEAR', max_length=16)),
                ('repeating_units', models.PositiveIntegerField()),
                ('monomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'abstract': False,
            },
            bases=('substance.simplesubstance',),
        ),
        migrations.CreateModel(
            name='Copolymer_monomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeating_units', models.PositiveIntegerField()),
                ('copolymer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polymer.Copolymer')),
                ('monomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
        ),
        migrations.AddField(
            model_name='copolymer',
            name='monomers',
            field=models.ManyToManyField(through='polymer.Copolymer_monomers', to='structure.Structure'),
        ),
    ]
