# Generated by Django 3.0.7 on 2020-06-15 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_flag', models.BooleanField(default=False)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChemdbInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemdbUser',
            fields=[
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('short', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeltingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_flag', models.BooleanField(default=False)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, editable=False)),
                ('public_to_user', models.BooleanField()),
                ('public', models.BooleanField()),
                ('code', models.CharField(max_length=64)),
                ('code_prefix', models.CharField(max_length=64)),
                ('smiles', models.CharField(blank=True, max_length=200, null=True)),
                ('standard_inchi', models.TextField(blank=True, null=True)),
                ('inchi_key', models.CharField(blank=True, max_length=27, null=True)),
                ('molar_mass', models.FloatField(blank=True, null=True)),
                ('iso_smiles', models.BooleanField(default=True, editable=False)),
                ('cas_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('chemspider_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('admin', models.ManyToManyField(related_name='chemicaldb_structure_admin', to='chemicaldb.ChemdbUser')),
                ('can_edit_institute', models.ManyToManyField(related_name='chemicaldb_structure_edit_institute', to='chemicaldb.ChemdbInstitute')),
                ('can_edit_user', models.ManyToManyField(related_name='chemicaldb_structure_can_edit', to='chemicaldb.ChemdbUser')),
                ('can_view_institute', models.ManyToManyField(related_name='chemicaldb_structure_view_institute', to='chemicaldb.ChemdbInstitute')),
                ('can_view_user', models.ManyToManyField(related_name='chemicaldb_structure_can_view', to='chemicaldb.ChemdbUser')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemicaldb_structure_owner', to='chemicaldb.ChemdbUser')),
            ],
            options={
                'permissions': (('add structure', 'Add Structure'),),
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True, editable=False)),
                ('public_to_user', models.BooleanField()),
                ('public', models.BooleanField()),
                ('code', models.CharField(max_length=64)),
                ('code_prefix', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('admin', models.ManyToManyField(related_name='chemicaldb_substance_admin', to='chemicaldb.ChemdbUser')),
                ('can_edit_institute', models.ManyToManyField(related_name='chemicaldb_substance_edit_institute', to='chemicaldb.ChemdbInstitute')),
                ('can_edit_user', models.ManyToManyField(related_name='chemicaldb_substance_can_edit', to='chemicaldb.ChemdbUser')),
                ('can_view_institute', models.ManyToManyField(related_name='chemicaldb_substance_view_institute', to='chemicaldb.ChemdbInstitute')),
                ('can_view_user', models.ManyToManyField(related_name='chemicaldb_substance_can_view', to='chemicaldb.ChemdbUser')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemicaldb_substance_owner', to='chemicaldb.ChemdbUser')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_chemicaldb.substance_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MixedSubstance',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Substance')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('chemicaldb.substance',),
        ),
        migrations.CreateModel(
            name='SimpleSubstance',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Substance')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('chemicaldb.substance',),
        ),
        migrations.CreateModel(
            name='StructureName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='chemicaldb.Structure')),
            ],
        ),
    ]
