# Generated by Django 3.0.7 on 2020-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0002_auto_20200615_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_structure_admin', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='can_edit_institute',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_structure_edit_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='can_edit_user',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_structure_can_edit', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='can_view_institute',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_structure_view_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='can_view_user',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_structure_can_view', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_substance_admin', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='can_edit_institute',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_substance_edit_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='can_edit_user',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_substance_can_edit', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='can_view_institute',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_substance_view_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='can_view_user',
            field=models.ManyToManyField(blank=True, related_name='chemicaldb_substance_can_view', to='chemicaldb.ChemdbUser'),
        ),
    ]
