# Generated by Django 3.0.6 on 2020-05-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0002_auto_20200522_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='valid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='structure',
            name='valid',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
