# Generated by Django 3.0.6 on 2020-06-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0003_auto_20200530_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='chemdbinstitute',
            name='parent_institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AddField(
            model_name='substance',
            name='substance_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chemicaldb.SubstanceClass'),
        ),
    ]
