# Generated by Django 3.0.7 on 2020-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0003_auto_20200617_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='public_to_institute',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='substance',
            name='public_to_institute',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='public_to_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='public_to_user',
            field=models.BooleanField(default=True),
        ),
    ]
