# Generated by Django 3.0.6 on 2020-06-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0005_auto_20200602_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substance',
            name='substance_class',
        ),
        migrations.DeleteModel(
            name='SubstanceClass',
        ),
    ]
