# Generated by Django 3.0.6 on 2020-06-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0006_auto_20200602_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='iso_smiles',
            new_name='smiles',
        ),
    ]
