# Generated by Django 3.0.6 on 2020-06-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0007_auto_20200602_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='iso_smiles',
            field=models.BooleanField(default=True),
        ),
    ]
