# Generated by Django 3.0.6 on 2020-06-02 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chemicaldb', '0008_structure_iso_smiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_chemicaldb.structure_set+', to='contenttypes.ContentType'),
        ),
    ]
