# Generated by Django 3.0.6 on 2020-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0009_structure_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='iso_smiles',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
