# Generated by Django 3.0.6 on 2020-06-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0010_auto_20200609_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='polymorphic_ctype',
        ),
    ]
