# Generated by Django 3.0.7 on 2020-06-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0011_remove_structure_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='structurename',
            unique_together={('structure', 'name')},
        ),
    ]
