# Generated by Django 3.0.7 on 2020-06-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0012_auto_20200610_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='admin',
            field=models.ManyToManyField(related_name='chemicaldb_structure_admin', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AddField(
            model_name='structure',
            name='can_edit_institute',
            field=models.ManyToManyField(related_name='chemicaldb_structure_edit_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AddField(
            model_name='structure',
            name='can_edit_user',
            field=models.ManyToManyField(related_name='chemicaldb_structure_can_edit', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AddField(
            model_name='structure',
            name='can_view_institute',
            field=models.ManyToManyField(related_name='chemicaldb_structure_view_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AddField(
            model_name='structure',
            name='can_view_user',
            field=models.ManyToManyField(related_name='chemicaldb_structure_can_view', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AddField(
            model_name='structure',
            name='code',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='code_prefix',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemicaldb_structure_owner', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AddField(
            model_name='structure',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='public_to_user',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemdbinstitute',
            name='parent_institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_institutes', to='chemicaldb.ChemdbInstitute'),
        ),
    ]
