# Generated by Django 3.0.7 on 2020-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0013_auto_20200611_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemdbinstitute',
            name='admin',
            field=models.ManyToManyField(related_name='administrating_institutes', to='chemicaldb.ChemdbUser'),
        ),
    ]
