# Generated by Django 3.0.7 on 2020-06-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0014_chemdbinstitute_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substance',
            old_name='user',
            new_name='owner',
        ),
    ]
