# Generated by Django 3.0.7 on 2020-06-12 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0015_auto_20200612_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='admin',
            field=models.ManyToManyField(related_name='chemicaldb_substance_admin', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AddField(
            model_name='substance',
            name='can_edit_institute',
            field=models.ManyToManyField(related_name='chemicaldb_substance_edit_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AddField(
            model_name='substance',
            name='can_edit_user',
            field=models.ManyToManyField(related_name='chemicaldb_substance_can_edit', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AddField(
            model_name='substance',
            name='can_view_institute',
            field=models.ManyToManyField(related_name='chemicaldb_substance_view_institute', to='chemicaldb.ChemdbInstitute'),
        ),
        migrations.AddField(
            model_name='substance',
            name='can_view_user',
            field=models.ManyToManyField(related_name='chemicaldb_substance_can_view', to='chemicaldb.ChemdbUser'),
        ),
        migrations.AddField(
            model_name='substance',
            name='code_prefix',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substance',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substance',
            name='public_to_user',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substance',
            name='code',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemicaldb_substance_owner', to='chemicaldb.ChemdbUser'),
        ),
    ]
