# Generated by Django 3.0.7 on 2020-06-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicaldb', '0016_auto_20200612_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='valid',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
