# Generated by Django 3.0.5 on 2020-05-18 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_flag', models.BooleanField(default=False)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeltingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('false_flag', models.BooleanField(default=False)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_smiles', models.CharField(blank=True, max_length=200, null=True)),
                ('standard_inchi', models.TextField(blank=True, null=True)),
                ('inchi_key', models.CharField(blank=True, max_length=27, null=True)),
                ('molar_mass', models.FloatField(blank=True, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('cas_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('chemspider_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=16, null=True, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MixedSubstance',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Substance')),
            ],
            bases=('chemicaldb.substance',),
        ),
        migrations.CreateModel(
            name='Polymer',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Substance')),
                ('polymer_structure_type', models.CharField(choices=[('LINEAR', 'linear'), ('BRANCHED', 'branched'), ('NETWORK', 'network')], default='LINEAR', max_length=16)),
                ('monomer_distribution', models.CharField(choices=[('GRADIENT', 'gradient'), ('STATISTICAL', 'statistical'), ('BLOCK', 'block')], default='STATISTICAL', max_length=16)),
                ('distribution_parameter', models.FloatField(default=1)),
            ],
            bases=('chemicaldb.substance',),
        ),
        migrations.CreateModel(
            name='PolymerStructure',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Structure')),
                ('big_smiles', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('chemicaldb.structure',),
        ),
        migrations.CreateModel(
            name='SimpleSubstance',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemicaldb.Substance')),
            ],
            bases=('chemicaldb.substance',),
        ),
        migrations.CreateModel(
            name='StructureName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='chemicaldb.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='Monomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeating_units', models.PositiveIntegerField()),
                ('monomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb.Structure')),
            ],
        ),
    ]
