# Generated by Django 3.0.5 on 2020-05-18 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemicaldb', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltingpoint',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Source'),
        ),
        migrations.AddField(
            model_name='meltingpoint',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb.Substance'),
        ),
        migrations.AddField(
            model_name='boilingpoint',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.Source'),
        ),
        migrations.AddField(
            model_name='boilingpoint',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb.Substance'),
        ),
        migrations.AddField(
            model_name='simplesubstance',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicaldb.Structure'),
        ),
        migrations.AddField(
            model_name='polymer',
            name='monomers',
            field=models.ManyToManyField(through='chemicaldb.Monomers', to='chemicaldb.Structure'),
        ),
        migrations.AddField(
            model_name='polymer',
            name='polymer_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polymer_structure', to='chemicaldb.PolymerStructure'),
        ),
        migrations.AddField(
            model_name='monomers',
            name='polymer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p', to='chemicaldb.Polymer'),
        ),
        migrations.AddField(
            model_name='mixedsubstance',
            name='structures',
            field=models.ManyToManyField(to='chemicaldb.Structure'),
        ),
    ]
