# Generated by Django 3.0.5 on 2020-05-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0001_initial'),
        ('chemicaldb', '0002_auto_20200518_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polymer',
            name='monomers',
        ),
        migrations.RemoveField(
            model_name='polymer',
            name='polymer_structure',
        ),
        migrations.RemoveField(
            model_name='polymer',
            name='substance_ptr',
        ),
        migrations.RemoveField(
            model_name='polymerstructure',
            name='structure_ptr',
        ),
        migrations.DeleteModel(
            name='Monomers',
        ),
        migrations.DeleteModel(
            name='Polymer',
        ),
        migrations.DeleteModel(
            name='PolymerStructure',
        ),
    ]
