# Generated by Django 2.2 on 2020-05-10 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeltingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substance.Substance')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.PropertySource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoilingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substance.Substance')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.PropertySource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleSubstance',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='substance.Substance')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
            ],
            options={
                'abstract': False,
            },
            bases=('substance.substance',),
        ),
        migrations.CreateModel(
            name='MixedSubstance',
            fields=[
                ('substance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='substance.Substance')),
                ('structures', models.ManyToManyField(to='structure.Structure')),
            ],
            options={
                'abstract': False,
            },
            bases=('substance.substance',),
        ),
    ]
