# Generated by Django 2.2 on 2020-05-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meltingpoint',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='meltingpoint',
            name='source',
        ),
        migrations.DeleteModel(
            name='BoilingPoint',
        ),
        migrations.DeleteModel(
            name='MeltingPoint',
        ),
    ]
