# Generated by Django 2.2 on 2020-05-10 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('substance', '0002_auto_20200510_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeltingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substance.Substance')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.PropertySource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoilingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substance.Substance')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.PropertySource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
