# Generated by Django 3.0.6 on 2020-05-11 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('substance', '0003_boilingpoint_meltingpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internal_Id',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substance.Substance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
