# Generated by Django 2.2 on 2020-05-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StructureName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.PropertySource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
