# Generated by Django 3.0.6 on 2020-05-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_molarmass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemspiderID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemspider_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StructureCASNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_number', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='structure',
            name='inchi_key',
            field=models.CharField(default='', max_length=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='iso_smiles',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='molar_mass',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='standard_inchi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MolarMass',
        ),
        migrations.AddField(
            model_name='structurecasnumber',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
        migrations.AddField(
            model_name='chemspiderid',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Structure'),
        ),
    ]
